# Note that changes to this file require a server restart to take effect.

############################
#
# ADMIN INTERFACE SETTINGS
#
############################
#
# These will be the values that admin interface users will choose from when
# updating a Service's accepted methods of payment. Make sure to update
# these values to match the ones in your data, as well as any additional
# ones you want to use that might not already be in your data.
#
# The list below should remain alphabetical, and should encompass all possible
# payment methods across all services.
accepted_payments:
- 'Cash'
- 'Check'
- 'Credit Card'
- 'EBT Card'
- 'Medicare'

# The email address that admin interface users should send questions/issues to.
# This link appears when an admin views their locations and organizations.
# See app/views/admin/locations/index.html.haml and
# app/views/admin/organizations/index.html.haml.
#
# Please make sure to change this to your own email address.
admin_support_email: ohanapi@codeforamerica.org

# These will be the values that admin interface users will choose from when
# updating an Organization's or Service's funding sources. Make sure to update
# these values to match the ones in your data, as well as any additional
# ones you want to use that might not already be in your data.
#
# The list below should remain in alphabetical order.
funding_sources:
- 'City'
- 'County'
- 'Donations'
- 'Dues'
- 'Endowments'
- 'Federal'
- 'Fees'
- 'Fundraising'
- 'Grants'
- 'Sales'
- 'Sponsorships'
- 'State'
- 'Taxes'
- 'United Way'

# An array of email domain names used by the admin interface to determine which
# users get to access which locations. For convenience, the API allows a client
# to retrieve locations that match a particular domain name. This means that
# when someone signs in to the admin interface with an organization email
# address, like "moncef@codeforamerica.org", then they will have access to all
# locations that match "codeforamerica.org". This works for these types of
# organization domain names, but if we allowed the same lookup for people with
# generic email addresses that end in "@gmail.com" for example, then they would
# be able to access all locations with "gmail.com" in the "email" field.
# To prevent that, the API compares the domain name with the list of generic
# domains that you define below, and if it finds it, then it looks for an exact
# match of the full email address.
#
# Depending on the email addresses present in your data, you might need to add
# domains to the list below. For example, in San Mateo County, many employees
# have a generic "@smcgov.org" email, even though they work in different
# departments, and should only be able to access their specific locations.
#
# This setting is used in 'app/models/concerns/search.rb'.
generic_domains:
  - gmail.com
  - aol.com
  - sbcglobal.net
  - hotmail.com
  - yahoo.com
  - comcast.net

# These will be the values that admin interface users will choose from when
# updating a Location's or a Service's languages. Make sure to update
# these values to match the ones in your data, as well as any additional
# ones you want to use that might not already be in your data.
#
# The list below should remain in alphabetical order.
languages:
- 'American Sign Language'
- 'Amharic'
- 'Arabic'
- 'Aramaic'
- 'Armenian'
- 'Assyrian'
- 'Bengali'
- 'Bosnian'
- 'Burmese'
- 'Cambodian'
- 'Cantonese'
- 'Cebuano'
- 'Chinese'
- 'Creole'
- 'Croatian'
- 'Czech'
- 'Danish'
- 'Dutch'
- 'Fijian'
- 'Filipino'
- 'Finnish'
- 'French'
- 'Fulani'
- 'Gaelic'
- 'German'
- 'Greek'
- 'Gujarati'
- 'Hausa'
- 'Hebrew'
- 'Hiligaynon'
- 'Hindi'
- 'Hmong'
- 'Hungarian'
- 'Igbo'
- 'Ilocano'
- 'Indonesian'
- 'Italian'
- 'Japanese'
- 'Kapampangan'
- 'Khmer'
- 'Kinyarwanda'
- 'Korean'
- 'Krio'
- 'Lao'
- 'Latvian'
- 'Maltese'
- 'Mandarin'
- 'Marathi'
- 'Mende'
- 'Mien'
- 'Mongolian'
- 'Ningbo'
- 'Norwegian'
- 'Oromo'
- 'Pangasinan'
- 'Persian'
- 'Polish'
- 'Portuguese'
- 'Punjabi'
- 'Romanian'
- 'Russian'
- 'Samoan'
- 'Serbo-Croatian'
- 'Shanghainese'
- 'Sindhi'
- 'Sinhalese'
- 'Somali'
- 'Spanish'
- 'Swahili'
- 'Swedish'
- 'Tagalog'
- 'Taiwanese'
- 'Tamil'
- 'Telugu'
- 'Temne'
- 'Thai'
- 'Tibetan'
- 'Tigrinya'
- 'Tongan'
- 'Ukrainian'
- 'Urdu'
- 'Vietnamese'
- 'Yiddish'
- 'Yoruba'

# These will be the values that admin interface users will choose from when
# updating a Service's required documents. Make sure to update
# these values to match the ones in your data, as well as any additional
# ones you want to use that might not already be in your data.
#
# The list below should remain in alphabetical order.
required_documents:
- 'Bank statements (last 3 months)'
- 'Government-issued picture identification'

# If your data contains a service_areas field that identifies which particular
# areas of a city or county are eligible for the services provided by an
# organization, and if you want to make sure that the service areas are always
# spelled the same way, then enter them below, one per line preceded by a dash
# and a space, just like the generic_domains above. Make sure to preserve the
# 2-space indentation. For example:
# valid_service_areas:
#   - 'Alameda County'
#   - 'Oakland'
#
# These will be the values that admin interface users will choose from when
# updating a Service's service areas. Make sure to update
# these values to match the ones in your data, as well as any additional
# ones you want to use that might not already be in your data.
#
# The list below should remain in alphabetical order.
valid_service_areas:
  - 'Alameda County'
  - 'Belmont'
  - 'Burlingame'
  - 'Colma'
  - 'Daly City'
  - 'East Palo Alto'
  - 'San Mateo County'
  - 'South San Francisco'

############################
#
# DATE SETTINGS
#
############################
#
# The date format to use for the Organization `date_incorporated` field,
# and for the Holiday Schedule `start_date` and `end_date` fields.
# The default format is the US-style month/day/year. To use the day/month
# style, change the value below to '%d/%m/'.
date_format: '%m/%d/'

############################
#
# EMAIL DELIVERY SETTINGS
#
############################
#
# The email address that confirmation emails are sent from after user signup,
# for the Developer and Admin portals.
# Please make sure to change this to your own email address.
confirmation_email: ohanapi@codeforamerica.org

###############################
#
# GEOGRAPHICAL BOUNDS SETTINGS
#
###############################
#
# Google provides a "bounds" option to restrict the address search to
# a particular area. This allows Google to disambiguate between two
# cities with the same name. For example, there is a city in San Mateo
# County called 'Brisbane'. There also happens to be a 'Brisbane' in
# Australia. If you didn't restrict the search to within San Mateo County,
# and you searched for locations near 'Brisbane', Google would look in
# Australia by default, and you wouldn't get any results.
#
# The bounds are defined by the SW and NE geo coordinates of your search area.
# It should be an array of two arrays. The first array should represent the
# SW coordinates, and the second the NE coordinates. Within each inner array,
# the coordinates should be Floats in [latitude, longitude] order. For example:
# bounds: [[37.1074, -122.521], [37.7084, -122.085]]
#
# The app is set to search within the continental US by default.
# Make sure to change the coordinates to match your preferred search area.
#
# This setting is used in 'app/models/concerns/search.rb'.
bounds: [[25.7084, -124.085], [48.9084, -67.085]]

###########################################
#
# SETTINGS FOR TESTS. PLEASE DO NOT MODIFY.
#
###########################################
test:
  accepted_payments:
  - 'Cash'
  - 'Check'

  bounds: [[37.1074, -122.521], [37.7084, -122.085]]

  confirmation_email: registration@ohanapi.org

  funding_sources:
  - 'State'
  - 'County'

  languages:
  - 'Arabic'
  - 'French'
  - 'Spanish'

  required_documents:
  - 'Bank Statement'
  - 'Picture ID'

  valid_service_areas:
  - 'Atherton'
  - 'Belmont'

  date_format: '%m/%d/'
admin_site: http://radical-api.sangparkllc.com/admin

##########################
#
# FEEDBACK EMAIL SETTINGS
#
##########################
#
# In the feedback_email section, you can add one or more email
# addresses (one per line) that should receive messages submitted
# by users who filled out the Feedback form. You can access the form
# by clicking the 'Feedback' link at the top right of the site.
#
# Make sure to change the email address below to your own,
# otherwise you won't receive any feedback emails.
feedback_email:
  to:
    - ivelyse@radical-health.com

##########################
#
# HOMEPAGE LINKS SETTINGS
#
##########################
#
# In the homepage_links section below, you can customize the
# text for the header and links that appear on the bottom half
# of the home page. There are two type of links, "general" and
# "emergency", which correspond to the two "boxes" on the homepage.
#
# To edit the header for each group of links, change the text of
# the keys that are indented below the "general:" or "emergency:" key.
# When we say "key", we refer to any entry in this file that ends with a colon.
# The items under the header key correspond to the text of the links
# under each header.
#
# Clicking a link on the homepage will perform a search for the full
# text of the link, unless the text contains words in parentheses, or
# two words separated by a slash. In those cases, a search will be
# performed for the first word only. For example, clicking on a
# "SNAP (Food Stamps)" or "SNAP/Food Stamps" link will search for "SNAP".
# Keep this in mind when editing or adding link text below.
#
# To add or replace a group of links, indent them below the "general:"
# and/or "emergency:" key. For example, to add a new group of general
# links, you would follow this format:
#
# general:
#   Header Text for New Group:
#     - text for link 1
#     - text for link 2
homepage_links:
  general:
    Government Assistance:
      - Health Insurance
      - Medicare
      - SFMNP (Food vouchers for seniors)
      - SNAP (Food Stamps)
      - 'WIC (Women, Infants, & Children)'

    Children, Teens, & Families:
      - Abuse Prevention
      - Child Care
      - Counseling
      - Mentoring Programs
      - Youth Development

  emergency:
    Emergency:
      - Psychiatric Emergency
      - Emergency Food
      - Emergency Shelter

    Reporting:
      - Domestic Violence
      - Child Abuse

####################
#
# INFO BOX SETTINGS
#
####################
#
# In this section, you can define the content for informational boxes that
# will appear at the top of the search results page whenever someone searches
# for a specific keyword or phrase that you define below.
# For example, if someone searches for "food stamps," you might want to display
# information about the federal SNAP program.
#
# To define a new info box, add a new entry indented under "info_box_terms:"
# using this format:
#
# info_box_terms:
#   short_name_for_your_info_box:
#     synonyms:
#       - synonym1
#       - synonym2
#       - synonym3
#     title: title for this info box
#     description:
#       description for this this info box
#     url: website that provides more info
#
# Once you define an info box, all fields are required except for the url.
#
# The name for your info box can be whatever you want. We recommend
# keeping it short and memorable, and making it all lowercase with
# underscores to separate words to keep it more readable.
#
# The synonyms are all the words, phrases, and acronyms that should
# trigger the info box. They must all be lowercase.
#
# The title and description are self-explanatory. On the website,
# the title will appear in bold above the description.
#
# If you provide an url, the "More info..." link in the info box
# will point to it.
#
# To see an info box in action, go to http://ohana-web-search-demo.herokuapp.com
# and search for "wic".
#
# By default, all info boxes use the same HTML template that looks like this:
# <dl>
#   <dt>title_of_info_box</dt>
#   <dd>info_box_description</dd>
#   <p>
#     <a href="info_box_url" target="_blank">More info...</a>
#   </p>
# </dl>
# This HTML is generated by the "render_info_box" method in
# app/helpers/info_box_helper.rb.
#
# If you would like to use a custom template for a particular info box,
# you can create the HTML for it in a partial in the
# "app/views/component/info_box/" directory. The partial must begin with
# an underscore.
# See app/view/component/info_box/_example_custom_template.html.haml for
# and example of a custom template.
#
# Once the template is created, you can assign it to an info box via the
# "custom:" field. An info box that uses a custom template only needs
# the "synonyms:" and "custom:" fields because you would be entering all
# the text directly in the custom template. The value of the "custom:" field
# should be the path to the partial, starting with "component", but without
# the underscore in the partial name. For example, to set up an info box that
# points to "_example_custom_template.html.haml", do this:
#
# info_box_terms:
#   custom_info_box:
#     synonyms:
#       - health care reform
#       - aca
#     custom: component/info_box/example_custom_template
info_box_terms:
  wic:
    synonyms:
      - wic
      - 'women, infants, and children'
      - 'women, infants, & children'
      - assistance for mothers
    title: 'Women, Infants, and Children'
    description:
      'Women, Infants, and Children (WIC)
      provides assistance for low-income pregnant, breastfeeding, and
      non-breastfeeding postpartum women, and to eligible infants and
      children up to age 5.'
    url: http://www.fns.usda.gov/wic

  sfmnp:
    synonyms:
      - sfmnp
      - senior farmers' market nutrition program
      - senior farmers market nutrition program
      - food vouchers for seniors
      - food vouchers
    title: Senior Farmers' Market Nutrition Program
    description:
      "Senior Farmers' Market Nutrition Program (SFMNP)
      provides low-income seniors with coupons that can be exchanged for eligible
      foods at farmers' markets, roadside stands, and community-supported
      agriculture programs."
    url: http://www.fns.usda.gov/sfmnp

  snap:
    synonyms:
      - snap
      - food stamps
      - calfresh
    title: SNAP
    description:
      'SNAP offers nutrition assistance to millions of eligible,
      low-income individuals and families and provides economic benefits to communities.'
    url: http://www.fns.usda.gov/snap/supplemental-nutrition-assistance-program-snap

###################################################################
#
# LANGUAGE TRANSLATION LINKS SETTINGS
#
###################################################################

# This represents the most common languages in your community.
# The languages will appear at the top of the home page, and
# clicking on each language will translate the text on the entire
# site into that language using Google Translate.
# The format should be 'Language: code', as shown below.
# To see a list of all supported languages and codes, read the
# "Language reference" section in the Google Translate documentation:
# https://cloud.google.com/translate/v2/translate-reference#supported_languages
# If you do not wish to include any language translation links,
# comment out or delete all of the language settings shown.
language_links:
  - 'English: en'
  - 'Español: es'
  - 'Tagalog: tl'
  - '中文: zh-CN'
  - 'العربية: ar'
  - 'Русский: ru'

######################
#
# SITE LOGO SETTINGS
#
######################
#
# This setting defines the filename for the site logo, which should be placed
# in the 'app/assets/images' directory. The site logo is the one that appears
# in the top left corner of the site.
site_logo: app_logo.png

######################
#
# SITE TITLE SETTINGS
#
######################
#
# This setting defines the HTML title for the site.
# It's the text that the browser displays at the top of the window or tab,
# and the text that the browser uses when saving a bookmark for this site.
#
# When viewing a page other than the homepage, this site title gets appended
# to the end of the page title. For example, if you were viewing the page for
# a location called "Health Insurance TeleCenter", the browser would display
# "Health Insurance TeleCenter | Ohana Web Search" as the page title.
site_title: Radical Health

###########################
#
# PHONE EXTENSION SETTING
#
###########################
#
# Defines the delimiter used for prefixing the phone extension field on the
# location details page. The extension appears after a phone number when
# present in the source dataset.
# Extensions are typically prefixed with 'Ext.', 'extension', or 'x'.
# To just provide a space between the phone number and extension leave this
# value blank or comment out the setting.
phone_extension_delimiter: x

###########################################
#
# SETTINGS FOR TESTS. PLEASE DO NOT MODIFY.
#
###########################################
test:
  admin_site: http://radical-api.sangparkllc.com/admin

  feedback_email:
    to:
      - ivelyse@radical-health.com

  homepage_links:
    general:
      Government Assistance:
        - Health Insurance
    emergency:
      Reporting:
        - Domestic Violence

  info_box_terms:
    wic:
      synonyms:
        - wic
        - 'women, infants, and children'
        - 'women, infants, & children'
        - assistance for mothers
      title: 'Women, Infants, and Children'
      description:
        'Women, Infants, and Children (WIC)
        provides assistance for low-income pregnant, breastfeeding, and
        non-breastfeeding postpartum women, and to eligible infants and
        children up to age 5.'
      url: http://www.fns.usda.gov/wic
    snap:
      synonyms:
        - snap
        - calfresh
      title: SNAP
      description: SNAP offers nutrition assistance to millions
    custom_info_box:
      synonyms:
        - health care reform
        - aca
      custom: component/info_box/example_custom_template


  site_title: Radical Health Web Search
